### ISSUE TITLE
Integrate with Real Time mod?

### ISSUE THREAD

**Issue by originalfoo** [CitiesSkylinesMods/AdditiveShader#2]
@dymanoid Can you think of any way that the dynamic sunrise/sunset times of Real Time mod could be somehow integrated with Additive Shader?

I'm not sure what the vanilla day/night change times are, but looking at some assets that use additive shader it seems farily common (for these asssets at least) that they are using `21 6` (on at 9 PM, off at 6 AM).

```
ShaderAsset(BuildingInfoSub lacantine-add):
 - ShaderInfo('AdditiveShader 7 1 20 1.5')
ShaderAsset(VehicleInfoSub tramcolor-add):
 - ShaderInfo('AdditiveShader 21 6 20 2')
ShaderAsset(VehicleInfoSub tramcolor-add):
 - ShaderInfo('AdditiveShader 21 6 20 2')
ShaderAsset(VehicleInfoSub tramcolor-add-trailer34(Clone)):
 - ShaderInfo('AdditiveShader 21 6 20 2 Instance')
ShaderAsset(VehicleInfoSub tramcolor-add-trailer1(Clone)):
 - ShaderInfo('AdditiveShader 21 6 20 2 Instance')
ShaderAsset(VehicleInfoSub tramcolor-add):
 - ShaderInfo('AdditiveShader 21 6 20 2')
ShaderAsset(VehicleInfoSub tramcolor-add):
 - ShaderInfo('AdditiveShader 21 6 20 2')
ShaderAsset(VehicleInfoSub tramcolor-add-trailer34(Clone)):
 - ShaderInfo('AdditiveShader 21 6 20 2 Instance')
ShaderAsset(VehicleInfoSub tramcolor-add-trailer2(Clone)):
 - ShaderInfo('AdditiveShader 21 6 20 2 Instance')
ShaderAsset(VehicleInfoSub tramcolor-add-trailer34(Clone)):
 - ShaderInfo('AdditiveShader 21 6 20 2 Instance')
ShaderAsset(VehicleInfoSub tramcolor-add-trailer1(Clone)):
 - ShaderInfo('AdditiveShader 21 6 20 2 Instance')
```

I'm thinking if vanilla has fairly static day/night boundary times, I could detect shaders that use those times(ish), flag them as "night time only" and have their on/off times then defined by a central source. Once that's in place, RT could get a method allowing it to change the values in the central source; now all the shaders that are "night time only" will turn on/off at the right time.

In theory I could even split those shaders in to separate list and update them just twice a day (or whenever day/night boundary is reached eg. for users messing with Time Warp mod).

As you've basically got an entire mod that plays with time, you've probably already found some high performance ways to do this kind of stuff?

**Comment by dymanoid** [comment]
I suppose you want to know the sunrise and sunset times?

You can query `SimulationManager.SUNRISE_HOUR` and `SimulationManager.SUNSET_HOUR`, Real Time updates these values once in 24 game hours.

Real Time has an additional category of "day/night" in therms of "city shall go to sleep" and "city shall awake", but since the shaders are visual stuff, it makes more sense to use the sunrise and sunset time.

What do you think?

**Comment by originalfoo** [comment]
The `SUNRISE_HOUR` and `SUNSET_HOUR` sound ideal for what the shaders seem to be doing, with added bonus they will sync with Real Time updates to day length!

ILSpy shows game uses following values:

```cs
public static float SUNRISE_HOUR = 5f; // 5AM
public static float SUNSET_HOUR = 20f; // 8 PM
```
That's 1 hour difference to what shaders seem to be using. I assume they want it to be "dark" before turning on, and turn off before it gets "light".

Digging arouind code that uses those values, I ended up in `DayNightProperties` which has these values which might be of interest at some point:

```cs
public float DayTime => Mathf.Clamp01(uMuS);

public float SunsetTime => Mathf.Clamp01((uMuS - 1f) * (1.5f / Mathf.Pow(m_RayleighScattering, 4f)));

public float NightTime => 1f - DayTime;
```

But then I also found:

```cs
SimulationManager.m_isNightTime
```

So for "on at night" shaders I can just set their visibility to `m_isNightTime` perhaps? Or just check to see when that changes (don't want to get in to transpiling as it seems overkill) and toggle all 'night only' shaders at that point... although that might cause a lag spike?

**Comment by originalfoo** [comment]
> Real Time has an additional category of "day/night" in therms of "city shall go to sleep" and "city shall awake", but since the shaders are visual stuff, it makes more sense to use the sunrise and sunset time.

I could potentially add an option to integrate with that; so if enabled it would use the "city sleep/wake" times rather than sunset/sunrise times?

I've added ability to tag shaders in the updated code, so potentially asset authors could tag their shaders with shift names, etc., allowing RT to toggle their shaders on/off when shifts start or end.

**Comment by dymanoid** [comment]
You indeed can use `m_isNightTime`:

```C#
m_simulationManager.m_isNightTime =
    (value < SimulationManager.SUNRISE_HOUR || value > SimulationManager.SUNSET_HOUR);
```

**Comment by originalfoo** [comment]
Seems to be working well now - shaders are turning on/off during acutal sunset/sunrise rather than the hard-coded vanilla times.
